### ISSUE TITLE
[BUG] - Scalar property requires domain/range

### ISSUE THREAD

**Issue by mprather** [opencaesar/oml#105]
## Description
Documentation states that scalar property can have zero or one domain/range+functional set.

http://www.opencaesar.io/oml/#ScalarProperty-LR

```
scalar property ID (:> [ScalarProperty|IRI] (, [ScalarProperty|IRI])*)? ([
  domain [Classifier|IRI]
  range [Scalar|IRI]
  functional?                // each instance can have a maximum of 1 value for this property
])?
```

## Steps to Reproduce
Define a scalar property without the axiom.
``` 
  scalar property MyProperty 
```

Result:
```
        The required feature 'domain' of 'ScalarProperty test:MyProperty' must be set
        The required feature 'range' of 'ScalarProperty test:MyProperty' must be set
        The required feature 'domain' of 'ScalarProperty test:MyProperty' must be set
        The required feature 'range' of 'ScalarProperty test:MyProperty' must be set
```

## Expected Behavior
Either the docs needs to be updated or there is a bug in the parsing code.

**Comment by melaasar** [comment]
The docs says that only the `functional` flag is optional (notated with `?` in BNF). Both `domain` and `range` do not have `?` which means they are required.

**Comment by mprather** [comment]
The entire section is wrapped by an optional ?

**(**[
  domain [Classifier|IRI]
  range [Scalar|IRI]
  functional?                // each instance can have a maximum of 1 value for this property
]**)?**

This is the point of this issue. The documentation is different than the behavior observed.

**Comment by melaasar** [comment]
Ah, sorry I missed that. You're right. I will fix this in the next patch release soon.

**Comment by melaasar** [comment]
I fixed the spec with the correct syntax. Please double check: http://www.opencaesar.io/om

**Comment by mprather** [comment]
Thanks. Closing.
