### ISSUE TITLE
Add support for OWL2 ObjectHasValue

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml#24]
## User Story
As a **vocabulary author**, I would like **support for an OML vocabulary to extend an OML description and support for OWL2's [Individual value restriction](https://www.w3.org/TR/owl2-syntax/#Individual_Value_Restriction)** so that **I could restrict the range of an OML relation for a given OML domain entity to be a particular OML instance.**.

## Detailed Description
Description providing additional details and context.

Here is a simple example of this idea:

-------------------------
description <http://example.org/D> with # as D {
    extends <V.oml>

    ci kind11 : V:Kind

    ci kind22 : V:Kind
}
----------------------

----------------------
vocabulary <http://example.org/V> with # as V {
    extends <D.oml>

    aspect A
    concept A1 :> A
    concept A2 :> A

    aspect B
    concept B1 :> B
    concept B2 :> B

    relation entity C [ 
        from A
        to B
        forward c
    ]

    concept Kind
    // With oml 0.5.0, one has to create entities for instances (i.e., an approximation of a singleton)
    // concept Kind11 :> Kind
    // concept Kind22 :> Kind

    relation entity CKind [
        from C
        to Kind
        forward cKind
    ]

    relation entity C11 :> C [
        from A1
        to B1
        forward c11
        // With oml 0.5.0
        // restricts all relation cKind to Kind11

        // OML syntax for OWL2 ObjectHasValue
        restricts object relation cKind to D:kind11
    ]

    relation entity C22 :> C [
        from A2
        to B2
        forward c22
        // With oml 0.5.0
        // restricts all relation cKind to Kind22

        // OML syntax for OWL2 ObjectHasValue
        restricts object relation cKind to D:kind22
    ]
}
---------------------

In OWl2 Functional Syntax, the above should include the following axioms:

-------------
ClassAssertion(D:kind11 V:Kind)
SubClassOf( ObjectHasValue(D:cKind D:kind11) V:C11)
-------------

## Acceptance Criteria
- [ ] Given **Support for OWL2 ObjectHasValue and vocabulary/description extends and description/vocabulary extends**, then **the above examples (adapted to the new OML textual syntax) should be well-formed with a well-defined mapping to OWL2 ObjectHasValue axioms.**

**Comment by NicolasRouquette** [comment]
One idea discussed w/ Steve Jenkins is borrowed from Scala's companion object for a class.
In the context of OML, the idea would be to allow in Tbox to declare companion individuals for any OML entity in scope of that Tbox. These companion individuals could then be used for restriction axioms (e.g., ObjectHasValue).

An alternative approach would be to relax OML such that a Tbox could import a Dbox. However, this could lead to some complications difficult to anticipate given the special nature of OML's bundle closure axioms.

**Comment by melaasar** [comment]
The fix here is to allow a Description to be imported by a Vocabulary using a "uses" import axiom. Then, an instance (concept instance or relation instance)  from that description can be used as a restricted value of a relation. Example:

uses <../daysofweek.oml>
concept Task1 :> scheduling:Task [
   restricts relationship deadline to daysofweek:Sunday // Sunday this is an instance of scheduling:Day
]

This is implemented in PR #32
