### ISSUE TITLE
Support for SWRL rule constructs needed for modeling composite structure semantics

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml#27]
## User Story
As a **caesar dev**, I would like **support in OML for specifying composite structure semantics** so that **we can explore using OML as syntax & semantics for SysML v2.**.

## Detailed Description
Description providing additional details and context.

Need to encode in OML SWRL rules the "role inclusion axioms" (RIA) found in this paper:
https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7535.pdf

One example is problematic with OML 0.5.0:

```
 (forall (?school ?teacher ?personTaught)
    (if (teaches ?teacher ?personTaught)
        (exists (?someSchool)
           (and (teacherAtSchool ?someSchool ?teacher)
                   (studentAtSchool ?someSchool ?personTaught))))) 
```

In SWRL, the above could be written as follows:

```
teaches(?teacher, ?personTaught) ^ 
teacherAtSchool(?school1, ?teacher) ^
studentAtSchool(?school2, ?personTaught)
=>
sameAs(?school1, ?school2)
```

To support this, OML needs to be extended to include support for the SWRL predicates `sameAs` and `differentFrom` ; see: https://www.w3.org/Submission/SWRL/#2.1

## Acceptance Criteria
- [ ] Given **OML with additional SWRL constructs**, then **all examples from the NISTIR 7535 report can be encoded in OML and support testing positive and negative examples.**

## Sub-task List
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by melaasar** [comment]
Support for sameAs and differentFrom predicates has been added to OML 0.7
