### ISSUE TITLE
[BUG] - vocabulary bundle should allow 'uses' similar to vocabulary.

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml#50]
## Description

Like the syntax for a vocabulary allows using a description, the syntax for a vocabulary bundle should allow using a description as well.

## Steps to Reproduce

The syntax for a vocabulary allows using a description, e.g.:

```
vocabulary <http://imce.jpl.nasa.gov/discipline/fse/fse> with # as fse {
  extends <http://imce.jpl.nasa.gov/foundation/project>
  extends <http://iso.org/80000-6-kindsOfQuantities>
  uses <http://iso.org/80000-3-instances>
  uses <http://iso.org/80000-4-instances>
  uses <http://iso.org/80000-5-instances>
  uses <http://iso.org/80000-6-instances>
```

This is not possible with a vocabulary bundle, e.g., the following is not allowed but it should be:

```
vocabulary bundle <http://imce.jpl.nasa.gov/foundation/bundle> with # as foundation-bundle {
  includes <http://imce.jpl.nasa.gov/foundation/project>
  uses <http://iso.org/80000-3-instances>
  uses <http://iso.org/80000-4-instances>
  uses <http://iso.org/80000-5-instances>
  uses <http://iso.org/80000-6-instances>
}
```

## Expected Behavior
A clear and concise description of what should be the expected behavior.

The above would allow the `foundation-bundle` to include instances of ISO 80K metrology definitions (units and kinds of quantities) to be reasoned about for bundle closure.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
Descriptions that are "used" by vocabularies will be transitively imported by the vocabulary bundle that includes those vocabularies. Does this address your concern?

**Comment by melaasar** [comment]
Please reopen if you still think this is not addressed by the previous comment.

**Comment by melaasar** [comment]
The use case you are describing for reasoning on the iso 80K instance libraries can be satisfied with a description bundle that includes them and that "use" the foundation vocabulary bundle.
