### ISSUE TITLE
[BUG] - Typo in the documentation of one of the ISO ontologies

### ISSUE THREAD

**Issue by hpdekoning** [opencaesar/oml#67]
## Description
There is a systematic documentation mismatch in the http://www.opencaesar.io/core-vocabularies//src/oml/iso.org/80000-*-instances webpages.

In clauses 4 and 5 the hyperlink bodies appear in the wrong 4.x and 5.x sub-clauses: they are out by one increment. E.g., "Types 80000-3-quantities:altitude" appears in 4.2, while it should be in sub-clause 4.1, etc.

## Steps to Reproduce
Reading the documentation.

## Expected Behavior
Documentation bodies under correct sub-clause headings.

## Additional Context
None

## Relevant screenshots
None

**Comment by melaasar** [comment]
This has been addressed, thanks!
e.g.: http://www.opencaesar.io/core-vocabularies/iso.org/80000-4-instances.html
