### ISSUE TITLE
[BUG] - 'general' missing in specification of Element

### ISSUE THREAD

**Issue by hpdekoning** [opencaesar/oml#68]
## Description
- [x]  The human readable specification of Element in http://www.opencaesar.io/oml/#Element misses the 'general' adjective to 'type'. The specification should presumably read as follows: Element is the most general type in the OML metamodel.
- [x] Typo: 'anumeration' should read 'enumeration' in http://www.opencaesar.io/oml/#SeparatorKind
- [x] In http://www.opencaesar.io/core-vocabularies/ the OML logo hyperlinks to www.openapis.org

## Steps to Reproduce
Reading the Ontological Modeling Language 0.8 specification.

## Expected Behavior
N.A.

## Additional Context
N.A.

## Relevant screenshots
N.A.

**Comment by melaasar** [comment]
All points were addressed. Thanks a lot for reporting those!
