### ISSUE TITLE
[QUESTION] - What is EJavaObject used for in the language spec?

### ISSUE THREAD

**Issue by hpdekoning** [opencaesar/oml#69]
## Description
In many places in the OML specification (e.g. http://www.opencaesar.io/oml/#BooleanLiteral) the `EJavaObject` type is referenced, typically with cardinality [0..1]. This looks like an implementation detail for the Xtext / Ecore implementation, but should probably not appear in the language specification. How should this be understood?

## Additional Context
N.A.

## Relevant screenshots
N.A.

**Comment by melaasar** [comment]
This has been fixed in OML 0.9.0 spec (http://www.opencaesar.io/oml/)
