### ISSUE TITLE
[BUG] - rdfs:Literal is a valid OWL2 datatype

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml#81]
## Description

`rdfs:Literal` is included in the list of IRIs in section 2.4: https://www.w3.org/TR/owl2-syntax/#IRIs

Furthermore, the datatype section explicitly refers to `rdfs:Literal`: https://www.w3.org/TR/owl2-syntax/#Datatypes

## Steps to Reproduce
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

## Expected Behavior
A clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
I added rdfs:Literal to the rdfs ontology:
https://github.com/opencaesar/core-vocabularies/blob/159faeca9f10a7078b5efa08ef79b526f980d38a/src/oml/www.w3.org/2000/01/rdf-schema.oml#L17
